name: Inspiration Log
favicon: null
layout_spectrum: 0
typography_spectrum: 0.42488
title: 'Inspiration Log || An art, designs, and people from around the world…'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-78303371-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#403732'
    - '#a6a19b'
    - '#d4cfc9'
    - '#67625e'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
